GSI-Xapiens-CSIRO/BGSI-GeneticAnalysisSupportPlatformIndonesia-GASPI

webgui/webapp/src/app/pages/admin-page/admin-page.component.html, webgui/webapp/src/app/pages/admin-page/admin-page.component.scss, webgui/webapp/src/app/pages/admin-page/admin-page.component.ts, webgui/webapp/src/app/pages/admin-page/components/admin-create-user-dialog/admin-create-user-dialog.component.html, webgui/webapp/src/app/pages/admin-page/components/admin-create-user-dialog/admin-create-user-dialog.component.spec.ts, webgui/webapp/src/app/pages/admin-page/components/admin-create-user-dialog/admin-create-user-dialog.component.ts, webgui/webapp/src/app/pages/admin-page/components/admin-user-click-dialog/admin-user-click-dialog.component.html, webgui/webapp/src/app/pages/admin-page/components/admin-user-click-dialog/admin-user-click-dialog.component.ts, webgui/webapp/src/app/pages/dportal-page/admin-section/admin-section.component.html
Create New Modal for Add User on Admin Page
Revamp Edit Interface
**there is some issue / error log from when register user**
=> Revamp Admin Page

.gitmodules, main.tf, webgui/webapp/src/app/pages/clinic-page/svep-submit/projects-list/projects-list.component.html, webgui/webapp/src/app/pages/clinic-page/svep-submit/projects-list/projects-list.component.ts, webgui/webapp/src/app/pages/clinic-page/svep-submit/svep-submit.component.ts, webgui/webapp/src/app/services/clinic.service.ts
sVEP has been updated to backend-end only. It has been included here as a module and the API URL is passed to the GAPSI front-end to link functionality
=> DEV: Integrate sVEP backend as a module and link the API in FE deployment

webgui/webapp/src/app/pages/admin-page/admin-page.component.ts, webgui/webapp/src/app/pages/admin-page/components/admin-create-user-dialog/admin-create-user-dialog.component.html, webgui/webapp/src/app/pages/admin-page/components/admin-create-user-dialog/admin-create-user-dialog.component.ts, webgui/webapp/src/app/pages/admin-page/components/admin-user-click-dialog/admin-user-click-dialog.component.html, webgui/webapp/src/app/pages/admin-page/services/admin.service.ts, webgui/webapp/src/app/pages/portal-page/dportal-page/admin-section/admin-notebooks-list/admin-notebook-item/admin-notebook-item.component.html, webgui/webapp/src/app/pages/portal-page/dportal-page/admin-section/admin-notebooks-list/admin-notebook-item/admin-notebook-item.component.ts, webgui/webapp/src/app/pages/portal-page/dportal-page/admin-section/admin-notebooks-list/admin-notebooks-list.component.ts, webgui/webapp/src/app/pages/portal-page/dportal-page/user-section/user-notebook-list/user-notebook-list.component.ts
- Add cost estimation on notebook list
=> Feat/cost estimations & UI user quota

webgui/webapp/src/app/pages/admin-page/admin-page.component.ts, webgui/webapp/src/app/pages/admin-page/components/admin-create-user-dialog/admin-create-user-dialog.component.ts, webgui/webapp/src/app/pages/admin-page/components/admin-user-click-dialog/admin-user-click-dialog.component.html, webgui/webapp/src/app/pages/admin-page/components/admin-user-click-dialog/admin-user-click-dialog.component.ts, webgui/webapp/src/app/services/dportal.service.ts
- Implement update user quota
- Add user quota service
=> feat: update user quota

webgui/webapp/src/app/pages/portal-page/dportal-page/user-section/user-file-list/user-file-list.component.ts
=> chore: add console list

webgui/webapp/src/app/pages/admin-page/admin-page.component.html, webgui/webapp/src/app/pages/admin-page/admin-page.component.ts
=> Page size 5 on admin page

webgui/webapp/src/app/pages/admin-page/admin-page.component.ts, webgui/webapp/src/app/pages/portal-page/dportal-page/user-section/user-file-list/user-file-list.component.ts, webgui/webapp/src/app/utils/file.ts
Handle convert data user usage.
=> handle convert user usage

webgui/webapp/src/app/pages/portal-page/dportal-page/admin-section/projects-list/projects-list.component.html, webgui/webapp/src/app/pages/portal-page/dportal-page/admin-section/projects-list/projects-list.component.ts, webgui/webapp/src/app/pages/portal-page/dportal-page/user-section/user-notebook-list/user-notebook-list.component.html, webgui/webapp/src/app/pages/portal-page/dportal-page/user-section/user-projects-list/user-projects-list.component.ts
Show Snack bar no more items when click next button (if data empty).
Move Input Notebook to top of card (my notebook).
Move Refresh and Index to top of card (project management)
=> Handle Next Button and Relayout

webgui/webapp/src/app/pages/portal-page/dportal-page/admin-section/projects-list/projects-list.component.html, webgui/webapp/src/app/pages/portal-page/dportal-page/admin-section/projects-list/projects-list.component.ts, webgui/webapp/src/app/pages/portal-page/dportal-page/user-section/user-notebook-list/user-notebook-list.component.html, webgui/webapp/src/app/pages/portal-page/dportal-page/user-section/user-projects-list/user-projects-list.component.ts
Show Snack bar no more items when click next button (if data empty).
Move Input Notebook to top of card (my notebook).
Move Refresh and Index to top of card (project management)
=> xapiens to main

webgui/webapp/src/app/app.component.html, webgui/webapp/src/app/app.component.scss, webgui/webapp/src/app/app.component.ts, webgui/webapp/src/app/components/profile-menu/profile-menu.component.html, webgui/webapp/src/app/components/profile-menu/profile-menu.component.scss, webgui/webapp/src/app/components/profile-menu/profile-menu.component.spec.ts, webgui/webapp/src/app/components/profile-menu/profile-menu.component.ts, webgui/webapp/src/app/pages/login-page/login-page.component.html, webgui/webapp/src/app/pages/login-page/login-page.component.ts, webgui/webapp/src/app/services/auth.service.ts
- Reset Password #90 
- User dropdown menu #89
=> Xapiens to main 0132

webgui/webapp/src/app/components/profile-menu/profile-menu.component.html, webgui/webapp/src/app/components/profile-menu/profile-menu.component.spec.ts, webgui/webapp/src/app/pages/login-page/login-page.component.html, webgui/webapp/src/app/pages/portal-page/dportal-page/user-section/user-notebook-list/user-notebook-list.component.html, webgui/webapp/src/app/pages/portal-page/dportal-page/user-section/user-projects-list/user-projects-list.component.html, webgui/webapp/src/app/pages/portal-page/dportal-page/user-section/user-section.component.html
=> fix layout user section at data portal

webgui/webapp/src/app/pages/portal-page/query-page/components/tabular-query-results-viewer/tabular-query-results-viewer.component.html, webgui/webapp/src/app/pages/portal-page/query-page/components/tabular-query-results-viewer/tabular-query-results-viewer.component.ts
Add Filter And Sorting => Dportal/Query
=> handle filter and sorting

webgui/webapp/src/app/pages/portal-page/dportal-page/user-section/user-notebook-list/user-notebook-list.component.scss
=> Hide Scrollbar on My Noteboos

webgui/webapp/src/app/pages/clinic-page/svep-submit/projects-list/projects-list.component.ts, webgui/webapp/src/app/pages/portal-page/filters-page/components/filters-tab/filters-tab.component.ts, webgui/webapp/src/app/pages/portal-page/query-page/components/query-tab/query-tab.component.ts, webgui/webapp/src/app/services/dportal.service.ts
Reverts GSI-Xapiens-CSIRO/BGSI-GeneticAnalysisSupportPlatformIndonesia-GASPI#98
=> Revert "fix: change params"

webgui/webapp/src/app/pages/admin-page/admin-page.component.html, webgui/webapp/src/app/pages/admin-page/admin-page.component.ts, webgui/webapp/src/app/pages/admin-page/components/admin-create-user-dialog/admin-create-user-dialog.component.ts, webgui/webapp/src/app/pages/portal-page/dportal-page/admin-section/admin-notebooks-list/admin-notebooks-list.component.html, webgui/webapp/src/app/pages/portal-page/dportal-page/admin-section/admin-notebooks-list/admin-notebooks-list.component.ts
Reverts GSI-Xapiens-CSIRO/BGSI-GeneticAnalysisSupportPlatformIndonesia-GASPI#107
=> Revert "Feat/pagination and search"

webgui/webapp/package.json, webgui/webapp/src/app/app.routes.ts, webgui/webapp/src/app/pages/clinic-page/clinic-page.component.html, webgui/webapp/src/app/pages/clinic-page/clinic-page.component.ts, webgui/webapp/src/app/pages/clinic-page/svep-igv/igv-viewer/igv-viewer.component.html, webgui/webapp/src/app/pages/clinic-page/svep-igv/igv-viewer/igv-viewer.component.spec.ts, webgui/webapp/src/app/pages/clinic-page/svep-igv/igv-viewer/igv-viewer.component.ts, webgui/webapp/src/app/pages/clinic-page/svep-igv/svep-igv.component.html, webgui/webapp/src/app/pages/clinic-page/svep-igv/svep-igv.component.spec.ts, webgui/webapp/src/app/pages/clinic-page/svep-igv/svep-igv.component.ts, webgui/webapp/src/types/igv.d.ts
=> igv viewer

webgui/webapp/src/app/pages/clinic-page/svep-igv/igv-viewer/igv-viewer.component.ts
=> change metode import

webgui/webapp/src/index.html
Reverts GSI-Xapiens-CSIRO/BGSI-GeneticAnalysisSupportPlatformIndonesia-GASPI#114
=> Revert "add allow csp from cdn"

webgui/webapp/src/app/pages/clinic-page/svep-igv/igv-viewer/igv-viewer.component.html, webgui/webapp/src/app/pages/clinic-page/svep-igv/igv-viewer/igv-viewer.component.ts, webgui/webapp/src/app/pages/clinic-page/svep-igv/svep-igv.component.html
Add a loading indicator when IGV Viewer is loading for the first time.
Update the instruction text (IGV Viewer)
=> Add Loading on IGV VIewer, Change Description

webgui/webapp/src/app/pages/clinic-page/clinic-page.component.html, webgui/webapp/src/app/pages/clinic-page/svep-results/annotation-viewer/annotation-viewer.component.html, webgui/webapp/src/app/pages/clinic-page/svep-results/annotation-viewer/annotation-viewer.component.ts, webgui/webapp/src/app/pages/clinic-page/svep-results/list-project-id/error-dialog/error-dialog.component.html, webgui/webapp/src/app/pages/clinic-page/svep-results/list-project-id/error-dialog/error-dialog.component.spec.ts, webgui/webapp/src/app/pages/clinic-page/svep-results/list-project-id/error-dialog/error-dialog.component.ts, webgui/webapp/src/app/pages/clinic-page/svep-results/list-project-id/list-project-id.component.html, webgui/webapp/src/app/pages/clinic-page/svep-results/list-project-id/list-project-id.component.spec.ts, webgui/webapp/src/app/pages/clinic-page/svep-results/list-project-id/list-project-id.component.ts, webgui/webapp/src/app/pages/clinic-page/svep-results/results-viewer/results-viewer.component.html, webgui/webapp/src/app/pages/clinic-page/svep-results/results-viewer/results-viewer.component.ts, webgui/webapp/src/app/pages/clinic-page/svep-results/svep-results.component.html, webgui/webapp/src/app/pages/clinic-page/svep-results/svep-results.component.scss, webgui/webapp/src/app/pages/clinic-page/svep-results/svep-results.component.ts, webgui/webapp/src/app/services/dportal.service.ts
- Change SVEP Result Tab Name
- Revamp Interface SVEP Result
- Integrate API Get List JOB id by Project
=> SVEP Result

webgui/webapp/src/app/pages/portal-page/dportal-page/admin-section/admin-folder-list/admin-folder-list.component.html, webgui/webapp/src/app/pages/portal-page/dportal-page/admin-section/admin-folder-list/admin-folder-list.component.scss
Add Scrolling on List User in File Management
=> add scroll at list user

webgui/webapp/src/app/pages/portal-page/dportal-page/admin-section/projects-list/project-assignments-dialog/project-assignments-dialog.component.ts
Only allow .txt file on (add snackbar)
=> handling only allow format from .txt

webgui/webapp/src/app/pages/clinic-page/svep-results/results-viewer/results-viewer.component.ts
Import Toaster Plugin issues after conflict with MAIN
=> add import toaster after merge

webgui/webapp/src/app/pages/clinic-page/svep-results/results-viewer/auto-complete/auto-complete.component.html, webgui/webapp/src/app/pages/clinic-page/svep-results/results-viewer/auto-complete/auto-complete.component.spec.ts, webgui/webapp/src/app/pages/clinic-page/svep-results/results-viewer/auto-complete/auto-complete.component.ts, webgui/webapp/src/app/pages/clinic-page/svep-results/results-viewer/results-viewer.component.html, webgui/webapp/src/app/pages/clinic-page/svep-results/results-viewer/results-viewer.component.ts
Change Component Drop down to Autocomplete
Create Component Based for autocomplete
Delete Each Filter
Re-Adjust Sorting
=> change dropdown to autocomplete

webgui/webapp/src/app/pages/clinic-page/svep-results/results-viewer/results-viewer.component.html, webgui/webapp/src/app/pages/clinic-page/svep-results/results-viewer/results-viewer.component.ts, webgui/webapp/src/app/pages/portal-page/dportal-page/user-section/user-notebook-list/notebook-item/notebook-item.component.html, webgui/webapp/src/app/pages/portal-page/dportal-page/user-section/user-notebook-list/notebook-item/notebook-item.component.ts
Add a few Hyperlink on clinical result
Add detail information in notebook
Add warning filter =! PASS on clinical result
=> handle tooltip and message box

webgui/webapp/src/app/pages/clinic-page/svep-submit/projects-list/projects-list.component.html, webgui/webapp/src/app/pages/clinic-page/svep-submit/projects-list/projects-list.component.ts, webgui/webapp/src/app/pages/clinic-page/svep-submit/qc-report/qc-report.component.html, webgui/webapp/src/app/pages/clinic-page/svep-submit/qc-report/qc-report.component.spec.ts, webgui/webapp/src/app/pages/clinic-page/svep-submit/qc-report/qc-report.component.ts, webgui/webapp/src/app/pages/clinic-page/svep-submit/svep-submit.component.html, webgui/webapp/src/app/pages/clinic-page/svep-submit/svep-submit.component.ts, webgui/webapp/src/app/services/clinic.service.ts
Feat: Integration of VCFSTATS
- Create Page
- API Integration
=> feat: vcfstat integration

webgui/webapp/src/app/pages/clinic-page/svep-results/results-viewer/results-viewer.component.ts, webgui/webapp/src/app/pages/clinic-page/svep-submit/projects-list/projects-list.component.html, webgui/webapp/src/app/pages/clinic-page/svep-submit/qc-report/qc-report.component.html, webgui/webapp/src/app/pages/clinic-page/svep-submit/qc-report/qc-report.component.ts
handle multiple error status on vcfstat graphic
handle multiple files on project list
=> Vcfstats graphic Error and Multiple File in Project list

webgui/webapp/src/app/app.component.html, webgui/webapp/src/app/app.component.scss, webgui/webapp/src/app/app.component.ts, webgui/webapp/src/app/components/list-menu/list-menu.component.html, webgui/webapp/src/app/components/list-menu/list-menu.component.scss, webgui/webapp/src/app/components/list-menu/list-menu.component.spec.ts, webgui/webapp/src/app/components/list-menu/list-menu.component.ts
- Create List Menu Component (move from main pages)
- Create List for Mobile and Desktop
- Remove Animation from .ts and change it into .scss
=> chore:re-Adjust Navbar

webgui/webapp/src/app/pages/clinic-page/clinic-results/list-project-id/list-project-id.component.html, webgui/webapp/src/app/pages/clinic-page/clinic-results/list-project-id/list-project-id.component.ts, webgui/webapp/src/app/pages/clinic-page/clinic-submit/projects-list/projects-list.component.html
Add Pemission only admin that can delete
Add Table header tittle for action
=> chore:add permission on delete vcf

webgui/webapp/src/app/pages/clinic-page/clinic-submit/qc-report/qc-report.component.ts
=> fix:rename description gq

webgui/webapp/src/app/pages/clinic-page/clinic-results/add-annotation-dialog/add-annotation-dialog.component.html, webgui/webapp/src/app/pages/clinic-page/clinic-results/annotation-viewer/annotation-viewer.component.html, webgui/webapp/src/app/pages/clinic-page/clinic-results/list-project-id/list-project-id.component.html, webgui/webapp/src/app/pages/clinic-page/clinic-results/svep-results-viewer/box-data/box-data.component.html, webgui/webapp/src/app/pages/clinic-page/clinic-results/svep-results-viewer/box-data/box-data.component.scss, webgui/webapp/src/app/pages/clinic-page/clinic-results/svep-results-viewer/box-data/box-data.component.ts, webgui/webapp/src/app/pages/clinic-page/clinic-submit/qc-report/qc-report.component.html
- Loading screen size on Generate QC Report
- Custom Color clignsign
- breakword on anotation and add line
=> fix:feedback

webgui/webapp/src/app/pages/portal-page/dportal-page/admin-section/projects-list/projects-list.component.html, webgui/webapp/src/app/pages/portal-page/dportal-page/user-section/user-notebook-list/user-notebook-list.component.html, webgui/webapp/src/app/pages/portal-page/dportal-page/user-section/user-notebook-list/user-notebook-list.component.ts
=> add tooltip on index and key

webgui/webapp/src/app/pages/clinic-page/clinic-results/pharmcat-results-viewer/box-data/box-data.component.html, webgui/webapp/src/app/pages/clinic-page/clinic-results/pharmcat-results-viewer/box-data/box-data.component.scss, webgui/webapp/src/app/pages/clinic-page/clinic-results/pharmcat-results-viewer/box-data/box-data.component.spec.ts, webgui/webapp/src/app/pages/clinic-page/clinic-results/pharmcat-results-viewer/box-data/box-data.component.ts, webgui/webapp/src/app/pages/clinic-page/clinic-results/pharmcat-results-viewer/pharmcat-results-viewer.component.html, webgui/webapp/src/app/pages/clinic-page/clinic-results/pharmcat-results-viewer/pharmcat-results-viewer.component.ts
Revamp Table PGXFLOW Cinical Result
=> chore:ravamp table

webgui/webapp/src/app/app.component.html
Reverts GSI-Xapiens-CSIRO/BGSI-GeneticAnalysisSupportPlatformIndonesia-GASPI#201
=> Revert "main to dev main"

webgui/webapp/src/app/pages/clinic-page/clinic-results/hub_configs.ts, webgui/webapp/src/app/pages/clinic-page/clinic-results/svep-results-viewer/box-data/box-data.component.html
Feat: Add AC,AN in config and show it on Box Data
=> Feat: Add AC,AN in config and show it on Box Data

webgui/webapp/src/app/pages/clinic-page/clinic-results/pharmcat-results-viewer/pharmcat-results-viewer.component.html, webgui/webapp/src/app/pages/clinic-page/clinic-results/pharmcat-results-viewer/pharmcat-results-viewer.component.ts
Feat Advanced Filter RSPON 
- Diplotypes
- Variants
=> feat: Advanced Filter RSPON (Diplotypes and Variants)

webgui/webapp/src/app/pages/clinic-page/clinic-results/pharmcat-results-viewer/pharmcat-results-viewer.component.html, webgui/webapp/src/app/pages/clinic-page/clinic-results/pharmcat-results-viewer/pharmcat-results-viewer.component.ts, webgui/webapp/src/app/services/clinic.service.ts
Advanced Filter on Diplotypes and Variants
=> FEAT: Advanced Filter RSPON

webgui/webapp/src/app/pages/clinic-page/clinic-results/no-results-alert/no-results-alert.component.html, webgui/webapp/src/app/pages/clinic-page/clinic-results/no-results-alert/no-results-alert.component.ts, webgui/webapp/src/app/pages/clinic-page/clinic-results/pharmcat-results-viewer/pharmcat-results-viewer.component.html
Get latest code from Main to dev main
=> Main to dev main

webgui/webapp/src/app/pages/clinic-page/clinic-results/annotation-viewer/annotation-viewer.component.ts, webgui/webapp/src/app/pages/clinic-page/clinic-results/clinic-results.component.html, webgui/webapp/src/app/pages/clinic-page/clinic-results/clinic-results.component.ts, webgui/webapp/src/app/pages/clinic-page/clinic-results/hybrid-results-viewer/hybrid-results-viewer.component.html, webgui/webapp/src/app/pages/clinic-page/clinic-results/hybrid-results-viewer/hybrid-results-viewer.component.ts, webgui/webapp/src/app/pages/clinic-page/clinic-results/lookup-results-viewer/lookup-results-viewer.component.html, webgui/webapp/src/app/pages/clinic-page/clinic-results/lookup-results-viewer/lookup-results-viewer.component.ts, webgui/webapp/src/app/pages/clinic-page/clinic-results/pharmcat-results-viewer/pharmcat-results-viewer.component.html, webgui/webapp/src/app/pages/clinic-page/clinic-results/pharmcat-results-viewer/pharmcat-results-viewer.component.ts, webgui/webapp/src/app/pages/clinic-page/clinic-results/pharmcat-results-viewer/rspon-box-data-view/rspon-box-data-view.component.html, webgui/webapp/src/app/pages/clinic-page/clinic-results/pharmcat-results-viewer/rspon-box-data-view/rspon-box-data-view.component.ts, webgui/webapp/src/app/pages/clinic-page/clinic-results/saved-for-reporting-viewer/saved-for-reporting-viewer.component.ts, webgui/webapp/src/app/pages/clinic-page/clinic-results/svep-results-viewer/box-data/box-data.component.html, webgui/webapp/src/app/pages/clinic-page/clinic-results/svep-results-viewer/box-data/box-data.component.ts, webgui/webapp/src/app/pages/clinic-page/clinic-results/svep-results-viewer/svep-results-viewer.component.html, webgui/webapp/src/app/pages/clinic-page/clinic-results/svep-results-viewer/svep-results-viewer.component.ts, webgui/webapp/src/app/utils/clinic.ts
Add Validation for duplicate Report
Add identifier on row if report already created
=> feat:add validation for duplicate reports and add identifier on list

terraform.tfvars.example
Get latest Dev main to UAT05/RSJPD
=> Dev main to UAT05/RSJPD
